Note creation and deletion
ScottasM/PPI-projektas pull request #21
Opened 2023-10-19 19:52 UTC by ZygimantasVidmantas

2023-10-19 21:46 UTC, jokubassilgalys approved these changes

2023-10-20 10:28 UTC, titasstank commented
Should probably make note creation UI close when clicking save for improved UX

2023-10-20 10:33 UTC, titasstank requested changes

2023-10-20 10:33 UTC, titasstank commented on PPI-projektas/objects/Note.cs
> +        var authorComparison = AuthorId.CompareTo(otherNote.AuthorId);
comparing by author id is pointless as it does not represent anything

2023-10-20 10:33 UTC, titasstank commented on PPI-projektas/Services/NoteService.cs
> +    public void DeleteNote(Guid noteId, Guid authorId)
change argument name to userId because it may not be the author

2023-10-24 19:48 UTC, ScottasM approved these changes

2023-10-25 17:44 UTC, titasstank approved these changes

2023-10-26 13:07 UTC, merged